# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('image_url', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=225)),
                ('page', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=225)),
                ('key', models.CharField(max_length=225)),
            ],
        ),
    ]
